CREATE TABLE payable (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         description VARCHAR(255),
                         amount NUMERIC(19, 2) NOT NULL,
                         expiration_date DATE,
                         payment_date DATE,
                         supplier_id BIGINT NOT NULL,

                         CONSTRAINT fk_payable_supplier
                             FOREIGN KEY (supplier_id)
                                 REFERENCES supplier(id)
);
