CREATE TABLE payable_importation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    error_message TEXT
);

CREATE TABLE payable_importation_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payable_id BIGINT,
    payable_importation_id BIGINT NOT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    error_message TEXT,

    CONSTRAINT fk_payable_importation_item_payable
        FOREIGN KEY (payable_id)
            REFERENCES payable(id),
    CONSTRAINT fk_payable_importation_item_importation
        FOREIGN KEY (payable_importation_id)
            REFERENCES payable_importation(id)
);

CREATE INDEX idx_payable_importation_item_importation_id
    ON payable_importation_item(payable_importation_id);
